### ISSUE TITLE
Cape Pin from Keeper Of The Lost Cities

### ISSUE THREAD

**Issue by entropical** [DrMikeG/PrusaMini#1]
Hey Dr Mike. I think I'm contacting the correct person. Apologies if I'm wrong.

My wife found a youtube video of you 3d printing a cape pin from Keeper Of The Lost Cities.

Are you able to share your STL? I found you have shared other files in github, but that model doesn't seem to be there. 

Thanks, Brock

**Comment by DrMikeG** [comment]
Hi. Sorry about that.
Shared here: https://github.com/DrMikeG/LostCitiesCostume
Let me know if you have any issues.

**Comment by entropical** [comment]
Perfect. Thanks so much for sharing.

In the interim, my wife asked my son to design one, and he did. He learned OnShape recently at school. In my son's one the eagle's head is pointing the wrong way. I'm not sure if that interferes with the flow of magic or not.

Have a good day, Brock
